[package]
name = "moar_options"
version = "0.1.1"
edition = "2021"
authors = ["Nils Feierabend <mztikk@outlook.de>"]
repository = "https://github.com/mztikk/more_options"
license = "MIT"
description = "library which adds more functionality to Option<T>"
